services:
  hkbus:
    image: hkbus
    container_name: hkbus
    hostname: hkbus
    restart: always
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        env: ${env}
    tty: true
    environment:
      env: ${env}
    ports:
      - ${port}:3000
    volumes:
      - ../src:/usr/src/app/src
      - ../public:/usr/src/app/public